from typing import Literal

from pydantic import BaseModel, Field


class InvestigationTask(BaseModel):
    """A single investigation task generated by the planner."""

    description: str = Field(
        description="What needs to be investigated."
    )

    source: Literal["github", "jira"] = Field(
        description="The enterprise system required for this task."
    )


class InvestigationPlan(BaseModel):
    """Structured investigation plan generated by the LLM."""

    project: str = Field(
    description="The project or product being investigated."
    )

    goal: str = Field(
        description="The main objective of the investigation."
    )

    tasks: list[InvestigationTask] = Field(
        description="Ordered investigation tasks."
    )

    required_sources: list[Literal["github", "jira"]] = Field(
        description="Enterprise systems required to complete the investigation."
    )